# github action 如何配置secret.ACCESS_TOKEN
# https://blog.csdn.net/ht370671963/article/details/111995883
name: spelling-react

on:
    push:
        branches:
            - 'main'

jobs:
    build:
        # 配置任务运行在最新的 Ubuntu Linux 运行器
        runs-on: ubuntu-latest
        steps:
            # 这是一个可以检出仓库代码到运行器的动作，它允许你运行脚本或者其他动作侵入你的代码（比如构建或者测试工具）
            - uses: actions/checkout@v3

            # 安装nodejs环境, actions/setup-node@v3动作安装指定版本的 Nodejs, 这会在你的 PATH 加上 node 和 npm 命令
            - name: install nodejs
              uses: actions/setup-node@v3
              with:
                  node-version: '16.x'

            # 安装依赖
            - name: install deps
              run: npm install --force

            # build
            # 使用deploy-github-pages-action后, 不需要build, 会自动build
            # - name: build apps
            #  run: npm run build

            # deploy
            # 使用action市场已有的action deploy-github-pages-action
            # https://github.com/marketplace/actions/deploy-github-pages
            - name: deploy apps
              uses: ptienchuan/deploy-github-pages-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
              with:
                  source-directory: 'dist'
                  target-branch: 'gh-pages'
                  user-name: 'ChristYoung'
                  user-email: '858851768@qq.com'